services:
  - type: web
    name: lexical-analyzer-api
    env: python
    buildCommand: "pip install -r api/requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT api.index:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
